### PR TITLE
Ajout d'un message à l'utilisateur quand il parle trop tot après sa connection

### PR DESCRIPTION
**Pull request by hadware**
Nécessite un redémarrage du serveur parce que j'ai rajouté la date dans le json envoyé quand tu parles trop tot

### CODE REVIEW

**Comment by mboevink** [comment]
Rather than adding a new check to the server would a Js timer have sufficed?


On 12 Nov 2017, at 5:39 pm, LePetitMarill <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #105<https://github.com/4577/loult-ng/pull/105>.

**Comment by ghost** [comment]
This is mostly against flooding scripts, which connect directly to the socket so they would bypass the js :(

**Comment by mboevink** [comment]
but in that case there is no issue dropping the message without warning.

Think about the new user that joins, types out a lengthy g'day only to have it disappear. Seems like exactly the same UI problem that lombre was talking about.

**Comment by hadware** [comment]
> implying  loult users type lenghty g'day messages

And if he wanted to resend it, he could just hit the up arrow like a boss and resend the same message after waiting for some time.

**Comment by ghost** [comment]
Could disable the input for the few seconds

**Comment by mboevink** [comment]
Says a lot about French technology when your phones still have up arrows lmoa


On 12 Nov 2017, at 11:39 pm, hadware <notifications@github.com<mailto:notifications@github.com>> wrote:


implying loult users type lenghty g'day messages

And if he wanted to resend it, he could just hit the up arrow like a boss and resend the same message after waiting for some time.

—

**Comment by hadware** [comment]
> going on the loult on your phone like a peasant

You keep disappointing me baudrive, you really do

**Comment by mboevink** [comment]
>You keep disappointing me baudrive, you really do

Words can hurt you know

**Pull request merged**
